### ISSUE TITLE
请问一下timeToGridX为什么要拿joinTime对timeScoreGrid的xlen进行取模，不太明白

### ISSUE THREAD

**Issue by f2ngwx** [ganlvtech/go-game-matching#1]
> func (m *Matcher) timeToGridX(joinTime Time) int {
	return int(joinTime) % m.timeScoreGrid.XLen()
}
先谢谢了

**Comment by f2ngwx** [comment]
是我理解错了，我还以为xlen一直是在增长的

**Comment by ganlvtech** [comment]
@f2ngwx 这个项目没有在线上运行过，不保证正确性。里面的思路可以随便拿去用，随便修改都可以，仅供参考。
